# config/routes.yaml
options_cors:
  path: /{any}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { _format: json }
  requirements:
    any: ".+"
  methods: [OPTIONS]
