name: transparentgrading

services:
  # 🌐 Nginx Reverse Proxy
  nginx:
    image: nginx:1.27-alpine
    container_name: tg-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./frontend/dist:/var/www/html/public/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tg-net

  # ⚙️ Symfony Backend (PHP-FPM)
  backend:
    build:
      context: ./backend
      target: prod
    container_name: tg-backend
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: mysql://tg_user:tg_pass@db:3306/transparentgrading
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - tg-net

  # 🖥️ Vue Frontend (Build über eigenes Dockerfile)
  frontend:
    build:
      context: ./frontend
      target: serve
    container_name: tg-frontend
    restart: unless-stopped
    networks:
      - tg-net

  # 🐬 MySQL Datenbank
  db:
    image: mysql:8.0
    container_name: tg-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transparentgrading
      MYSQL_USER: tg_user
      MYSQL_PASSWORD: tg_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tg-net

volumes:
  db_data:

networks:
  tg-net:
    name: tg-net
    driver: bridge
