services:
  - type: web
    name: transparentgrading
    env: docker
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: ""
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://transparent-grading-flax.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, PATCH, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Requested-With
